server:
  port: 9999
  #port: ${PORT:0}
spring:
  data:
    mongodb:
      host: 3.144.30.186
      port: 27017
      database: mutant
  application:
    name: mutant
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: web
    service:
      name: mutant
  activemq:
    brokerUrl: tcp://3.144.255.41:61616
    user: admin
    password: oGMoPt87ZaZt
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}-${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://3.144.211.167:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
